[env:M5PaperS3]
platform = espressif32@6.10.0
board = esp32-s3-devkitm-1
monitor_speed = 115200
framework = arduino
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
    -D fileencoding=utf-8
lib_deps = 
	m5stack/M5Unified@0.2.5
	m5stack/M5GFX@0.2.6
	epdiy=https://github.com/vroland/epdiy.git#d84d26ebebd780c4c9d4218d76fbe2727ee42b47 
