name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install PlatformIO
      run: |
        pip install --upgrade pip
        pip install platformio

    - name: Build with PlatformIO
      run: pio run

    - name: Run unit tests
      run: pio test